---
- name: Enable service {{ ssm_package }} and ensure it is not masked
  service:
    name: "{{ ssm_package }}"
    enabled: yes
  notify: Start {{ ssm_logrotate_daemon }} on Amazon Linux 1
  tags:
    - enable-service

- name: Deploy {{ ssm_package }} logrotate configuration file
  template:
    src: logrotate/aws-ssm-agent.j2
    dest: "{{ ssm_logrotate_config_file }}"
    force: true
  notify: Reload {{ ssm_logrotate_daemon }}
  tags:
    - deploy-logrotate-config
