---
# - name: Add {{ ssm_package }} key
#   rpm_key:
#     state: present
#     key: "{{ ssm_package_gpg }}"
#   tags:
#     - add-key
#     - download
#     - install

# - name: Download {{ ssm_package }}.rpm.sig
#   get_url:
#     url: "{{ ssm_package_signature }}"
#     dest: "/{{ ssm_temp_path }}/{{ ssm_package }}.rpm.sig"
#     timeout: "{{ ssm_global_downloads_timeout }}"
#   tags:
#     - download-signature
#     - verify-signature
#     - download
#     - install

- name: Download {{ ssm_package }}.rpm
  get_url:
    url: "{{ ssm_package_url }}"
    dest: "/{{ ssm_temp_path }}/{{ ssm_package }}.rpm"
    timeout: "{{ ssm_global_downloads_timeout }}"
  tags:
    - download
    - verify-signature
    - install

# - name: Verify {{ ssm_package }} package signature
#   command: gpg --verify {{ ssm_package }}.rpm.sig {{ ssm_package }}.rpm
#   register: verified_sig
#   failed_when: "'BAD' in verified_sig.stderr"
#   changed_when: false
#   args:
#     chdir: "{{ ssm_temp_path }}"
#   tags:
#     - verify-signature
#     - install

- name: Install {{ ssm_package }}.rpm
  yum:
    name: "/{{ ssm_temp_path }}/{{ ssm_package }}.rpm"
    state: present
  tags:
    - install
