---
- name: update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  tags:
    - update-cache

# - name: Add {{ ssm_package }} key
#   apt_key:
#     state: present
#     url: "{{ ssm_package_gpg }}"
#   tags:
#     - add-key
#     - download
#     - install

# - name: Download {{ ssm_package }}.deb.sig
#   get_url:
#     url: "{{ ssm_package_url }}"
#     dest: "/{{ temp_path }}/{{ ssm_package }}.deb.sig"
#     timeout: "{{ ssm_global_downloads_timeout }}"
#   tags:
#     - download-signature
#     - verify-signature
#     - download
#     - install

- name: Download {{ ssm_package }}.deb
  get_url:
    url: "{{ ssm_package_url }}"
    dest: "/{{ temp_path }}/{{ ssm_package }}.deb"
    timeout: "{{ ssm_global_downloads_timeout }}"
  tags:
    - download
    - verify-signature
    - install

# - name: Verify {{ ssm_package }} package signature
#   command: gpg --verify {{ ssm_package }}.deb.sig {{ ssm_package }}.deb
#   register: verified_sig
#   failed_when: "'BAD' in verified_sig.stderr"
#   changed_when: false
#   args:
#     chdir: "{{ ssm_temp_path }}"
#   tags:
#     - verify-signature
#     - install

- name: Install {{ ssm_package }}.deb
  apt:
    deb: "/{{ temp_path }}/{{ ssm_package }}.deb"
    state: present
  tags:
    - install
